// <auto-generated />
using System;
using Gkts.Karargah;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gkts.Karargah.Migrations
{
    [DbContext(typeof(KarargahDbContext))]
    partial class KarargahDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gkts.Karargah.TaktikVeriPaketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirlikAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Boylam")
                        .HasColumnType("double precision");

                    b.Property<double>("Enlem")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("KayitZamani")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Saglik")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaktikVeriler");
                });
#pragma warning restore 612, 618
        }
    }
}
